=== YasirArfat1/xml/dataformating.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

    <xs:element name="aptech">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="student" maxOccurs="unbounded">
                        <xs:complexType mixed="false">
                            <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                                <xs:choice>
                                    <xs:element name="email" type="xs:string" />
                                    <xs:element name="number" type="xs:string" />
                                </xs:choice>
                                <xs:element name="age" type="xs:int"/>
                                <xs:element name="pass" type="xs:boolean"/>
                                <xs:element name="dob" type="xs:date"></xs:element>
                                <xs:element name="time" type="xs:time"></xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="faculty" maxOccurs="unbounded">

                    </xs:element>
                </xs:sequence>
            </xs:complexType>
    </xs:element>
</xs:schema>

=== YasirArfat1/xml/myaptechdata.xml
<?xml version="1.0"?>

<aptech xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com dataformating.xsd">
   <student>

    <name>Hamza Khan</name>
    <number>0317-4455210</number>
    <age>24</age>
    <pass>true</pass>
    <dob>1998-02-28</dob>
    <time>00:01:00</time>
   </student>


   <student>
    <name>Ali</name>
    <email>ali@gmail.com</email>
    <age>24</age>
    <pass>true</pass>
    <dob>1998-02-28</dob>
    <time>00:01:00</time>
   </student>



   <faculty>

   </faculty>

   
</aptech>
