=== YasirArfat1/xml/format.dtd
<!ELEMENT aptech (student+, faculty+)>
    <!ELEMENT student (id,name,class,(email | number))>
    <!ELEMENT faculty (name,email,password)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT password (#PCDATA)>

    
   

    <!ATTLIST aptech center CDATA #REQUIRED>
    <!ATTLIST faculty semester CDATA #IMPLIED>
    <!ATTLIST email domain CDATA #FIXED "gmail">

=== YasirArfat1/xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE aptech SYSTEM  "format.dtd" [
<!ENTITY cp  "cpism">
<!ENTITY ps  "pass1122">

]>

<aptech center="SFC">
    <student>
        <id>1</id>
        <name>Hamza</name>
        <class>&cp;</class>
        <email domain="gmail">hamza@gmail.com</email>
    </student>
    
    <student>
        <id>1</id>
        <name>Hamza</name>
        <class>&cp;</class>
        <number>0312-9939222</number>
    </student>


    <faculty semester="CPISM">
        <name>Yasir</name>
        <email domain="gmail">yair@gmail.com</email>
        <password>12323</password>
    </faculty>

    <faculty>
        <name>Yasir</name>
        <email>yair@gmail.com</email>
        <password>12323</password>
    </faculty>


    <faculty>
        <name>Yasir</name>
        <email>yair@gmail.com</email>
        <password>12323</password>
    </faculty>

    <faculty>
        <name>Yasir</name>
        <email>yair@gmail.com</email>
        <password>&ps;</password>
    </faculty>

    
</aptech>
